/* tslint:disable */
/* eslint-disable */
/**
 * Faros
 * Resource for managing Faros workspaces
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mangirdas@judeikis.LT
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { OidcClaimSource } from './OidcClaimSource';
import {
    OidcClaimSourceFromJSON,
    OidcClaimSourceFromJSONTyped,
    OidcClaimSourceToJSON,
} from './OidcClaimSource';

/**
 * 
 * @export
 * @interface OidcIDToken
 */
export interface OidcIDToken {
    /**
     * 
     * @type {string}
     * @memberof OidcIDToken
     */
    accessTokenHash: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof OidcIDToken
     */
    audience: Array<string>;
    /**
     * 
     * @type {Date}
     * @memberof OidcIDToken
     */
    expiry: Date;
    /**
     * 
     * @type {Date}
     * @memberof OidcIDToken
     */
    issuedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof OidcIDToken
     */
    issuer: string;
    /**
     * 
     * @type {string}
     * @memberof OidcIDToken
     */
    nonce: string;
    /**
     * 
     * @type {string}
     * @memberof OidcIDToken
     */
    subject: string;
    /**
     * 
     * @type {string}
     * @memberof OidcIDToken
     */
    claims: string;
    /**
     * 
     * @type {{ [key: string]: OidcClaimSource; }}
     * @memberof OidcIDToken
     */
    distributedClaims: { [key: string]: OidcClaimSource; };
    /**
     * 
     * @type {string}
     * @memberof OidcIDToken
     */
    sigAlgorithm: string;
}

/**
 * Check if a given object implements the OidcIDToken interface.
 */
export function instanceOfOidcIDToken(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "accessTokenHash" in value;
    isInstance = isInstance && "audience" in value;
    isInstance = isInstance && "expiry" in value;
    isInstance = isInstance && "issuedAt" in value;
    isInstance = isInstance && "issuer" in value;
    isInstance = isInstance && "nonce" in value;
    isInstance = isInstance && "subject" in value;
    isInstance = isInstance && "claims" in value;
    isInstance = isInstance && "distributedClaims" in value;
    isInstance = isInstance && "sigAlgorithm" in value;

    return isInstance;
}

export function OidcIDTokenFromJSON(json: any): OidcIDToken {
    return OidcIDTokenFromJSONTyped(json, false);
}

export function OidcIDTokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): OidcIDToken {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accessTokenHash': json['AccessTokenHash'],
        'audience': json['Audience'],
        'expiry': (new Date(json['Expiry'])),
        'issuedAt': (new Date(json['IssuedAt'])),
        'issuer': json['Issuer'],
        'nonce': json['Nonce'],
        'subject': json['Subject'],
        'claims': json['claims'],
        'distributedClaims': (mapValues(json['distributedClaims'], OidcClaimSourceFromJSON)),
        'sigAlgorithm': json['sigAlgorithm'],
    };
}

export function OidcIDTokenToJSON(value?: OidcIDToken | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'AccessTokenHash': value.accessTokenHash,
        'Audience': value.audience,
        'Expiry': (value.expiry.toISOString()),
        'IssuedAt': (value.issuedAt.toISOString()),
        'Issuer': value.issuer,
        'Nonce': value.nonce,
        'Subject': value.subject,
        'claims': value.claims,
        'distributedClaims': (mapValues(value.distributedClaims, OidcClaimSourceToJSON)),
        'sigAlgorithm': value.sigAlgorithm,
    };
}

