/* tslint:disable */
/* eslint-disable */
/**
 * Faros
 * Resource for managing Faros workspaces
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mangirdas@judeikis.LT
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { V1ListMeta } from './V1ListMeta';
import {
    V1ListMetaFromJSON,
    V1ListMetaFromJSONTyped,
    V1ListMetaToJSON,
} from './V1ListMeta';
import type { V1alpha1Organization } from './V1alpha1Organization';
import {
    V1alpha1OrganizationFromJSON,
    V1alpha1OrganizationFromJSONTyped,
    V1alpha1OrganizationToJSON,
} from './V1alpha1Organization';

/**
 * 
 * @export
 * @interface V1alpha1OrganizationList
 */
export interface V1alpha1OrganizationList {
    /**
     * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
     * @type {string}
     * @memberof V1alpha1OrganizationList
     */
    apiVersion?: string;
    /**
     * 
     * @type {Array<V1alpha1Organization>}
     * @memberof V1alpha1OrganizationList
     */
    items: Array<V1alpha1Organization>;
    /**
     * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
     * @type {string}
     * @memberof V1alpha1OrganizationList
     */
    kind?: string;
    /**
     * 
     * @type {V1ListMeta}
     * @memberof V1alpha1OrganizationList
     */
    metadata?: V1ListMeta;
}

/**
 * Check if a given object implements the V1alpha1OrganizationList interface.
 */
export function instanceOfV1alpha1OrganizationList(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "items" in value;

    return isInstance;
}

export function V1alpha1OrganizationListFromJSON(json: any): V1alpha1OrganizationList {
    return V1alpha1OrganizationListFromJSONTyped(json, false);
}

export function V1alpha1OrganizationListFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1alpha1OrganizationList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'apiVersion': !exists(json, 'apiVersion') ? undefined : json['apiVersion'],
        'items': ((json['items'] as Array<any>).map(V1alpha1OrganizationFromJSON)),
        'kind': !exists(json, 'kind') ? undefined : json['kind'],
        'metadata': !exists(json, 'metadata') ? undefined : V1ListMetaFromJSON(json['metadata']),
    };
}

export function V1alpha1OrganizationListToJSON(value?: V1alpha1OrganizationList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'apiVersion': value.apiVersion,
        'items': ((value.items as Array<any>).map(V1alpha1OrganizationToJSON)),
        'kind': value.kind,
        'metadata': V1ListMetaToJSON(value.metadata),
    };
}

