/* tslint:disable */
/* eslint-disable */
/**
 * Faros
 * Resource for managing Faros workspaces
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mangirdas@judeikis.LT
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { V1ObjectReference } from './V1ObjectReference';
import {
    V1ObjectReferenceFromJSON,
    V1ObjectReferenceFromJSONTyped,
    V1ObjectReferenceToJSON,
} from './V1ObjectReference';

/**
 * 
 * @export
 * @interface V1alpha1WorkspaceSpec
 */
export interface V1alpha1WorkspaceSpec {
    /**
     * 
     * @type {string}
     * @memberof V1alpha1WorkspaceSpec
     */
    description?: string;
    /**
     * 
     * @type {V1ObjectReference}
     * @memberof V1alpha1WorkspaceSpec
     */
    organizationRef?: V1ObjectReference;
}

/**
 * Check if a given object implements the V1alpha1WorkspaceSpec interface.
 */
export function instanceOfV1alpha1WorkspaceSpec(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function V1alpha1WorkspaceSpecFromJSON(json: any): V1alpha1WorkspaceSpec {
    return V1alpha1WorkspaceSpecFromJSONTyped(json, false);
}

export function V1alpha1WorkspaceSpecFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1alpha1WorkspaceSpec {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': !exists(json, 'description') ? undefined : json['description'],
        'organizationRef': !exists(json, 'organizationRef') ? undefined : V1ObjectReferenceFromJSON(json['organizationRef']),
    };
}

export function V1alpha1WorkspaceSpecToJSON(value?: V1alpha1WorkspaceSpec | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': value.description,
        'organizationRef': V1ObjectReferenceToJSON(value.organizationRef),
    };
}

