/* tslint:disable */
/* eslint-disable */
/**
 * Faros
 * Resource for managing Faros workspaces
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mangirdas@judeikis.LT
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1alpha1Condition
 */
export interface V1alpha1Condition {
    /**
     * 
     * @type {string}
     * @memberof V1alpha1Condition
     */
    lastTransitionTime: string;
    /**
     * 
     * @type {string}
     * @memberof V1alpha1Condition
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof V1alpha1Condition
     */
    reason?: string;
    /**
     * 
     * @type {string}
     * @memberof V1alpha1Condition
     */
    severity?: string;
    /**
     * 
     * @type {string}
     * @memberof V1alpha1Condition
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof V1alpha1Condition
     */
    type: string;
}

/**
 * Check if a given object implements the V1alpha1Condition interface.
 */
export function instanceOfV1alpha1Condition(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "lastTransitionTime" in value;
    isInstance = isInstance && "status" in value;
    isInstance = isInstance && "type" in value;

    return isInstance;
}

export function V1alpha1ConditionFromJSON(json: any): V1alpha1Condition {
    return V1alpha1ConditionFromJSONTyped(json, false);
}

export function V1alpha1ConditionFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1alpha1Condition {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'lastTransitionTime': json['lastTransitionTime'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'reason': !exists(json, 'reason') ? undefined : json['reason'],
        'severity': !exists(json, 'severity') ? undefined : json['severity'],
        'status': json['status'],
        'type': json['type'],
    };
}

export function V1alpha1ConditionToJSON(value?: V1alpha1Condition | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'lastTransitionTime': value.lastTransitionTime,
        'message': value.message,
        'reason': value.reason,
        'severity': value.severity,
        'status': value.status,
        'type': value.type,
    };
}

