//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by kcp code-generator. DO NOT EDIT.

package v1alpha1

import (
	kcpcache "github.com/kcp-dev/apimachinery/v2/pkg/cache"
	"github.com/kcp-dev/logicalcluster/v3"

	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"

	tenancyv1alpha1 "github.com/faroshq/faros/pkg/apis/tenancy/v1alpha1"
)

// MetadataClusterLister can list Metadatas across all workspaces, or scope down to a MetadataLister for one workspace.
// All objects returned here must be treated as read-only.
type MetadataClusterLister interface {
	// List lists all Metadatas in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*tenancyv1alpha1.Metadata, err error)
	// Cluster returns a lister that can list and get Metadatas in one workspace.
	Cluster(clusterName logicalcluster.Name) MetadataLister
	MetadataClusterListerExpansion
}

type metadataClusterLister struct {
	indexer cache.Indexer
}

// NewMetadataClusterLister returns a new MetadataClusterLister.
// We assume that the indexer:
// - is fed by a cross-workspace LIST+WATCH
// - uses kcpcache.MetaClusterNamespaceKeyFunc as the key function
// - has the kcpcache.ClusterIndex as an index
func NewMetadataClusterLister(indexer cache.Indexer) *metadataClusterLister {
	return &metadataClusterLister{indexer: indexer}
}

// List lists all Metadatas in the indexer across all workspaces.
func (s *metadataClusterLister) List(selector labels.Selector) (ret []*tenancyv1alpha1.Metadata, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*tenancyv1alpha1.Metadata))
	})
	return ret, err
}

// Cluster scopes the lister to one workspace, allowing users to list and get Metadatas.
func (s *metadataClusterLister) Cluster(clusterName logicalcluster.Name) MetadataLister {
	return &metadataLister{indexer: s.indexer, clusterName: clusterName}
}

// MetadataLister can list all Metadatas, or get one in particular.
// All objects returned here must be treated as read-only.
type MetadataLister interface {
	// List lists all Metadatas in the workspace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*tenancyv1alpha1.Metadata, err error)
	// Get retrieves the Metadata from the indexer for a given workspace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*tenancyv1alpha1.Metadata, error)
	MetadataListerExpansion
}

// metadataLister can list all Metadatas inside a workspace.
type metadataLister struct {
	indexer     cache.Indexer
	clusterName logicalcluster.Name
}

// List lists all Metadatas in the indexer for a workspace.
func (s *metadataLister) List(selector labels.Selector) (ret []*tenancyv1alpha1.Metadata, err error) {
	err = kcpcache.ListAllByCluster(s.indexer, s.clusterName, selector, func(i interface{}) {
		ret = append(ret, i.(*tenancyv1alpha1.Metadata))
	})
	return ret, err
}

// Get retrieves the Metadata from the indexer for a given workspace and name.
func (s *metadataLister) Get(name string) (*tenancyv1alpha1.Metadata, error) {
	key := kcpcache.ToClusterAwareKey(s.clusterName.String(), "", name)
	obj, exists, err := s.indexer.GetByKey(key)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(tenancyv1alpha1.Resource("Metadata"), name)
	}
	return obj.(*tenancyv1alpha1.Metadata), nil
}

// NewMetadataLister returns a new MetadataLister.
// We assume that the indexer:
// - is fed by a workspace-scoped LIST+WATCH
// - uses cache.MetaNamespaceKeyFunc as the key function
func NewMetadataLister(indexer cache.Indexer) *metadataScopedLister {
	return &metadataScopedLister{indexer: indexer}
}

// metadataScopedLister can list all Metadatas inside a workspace.
type metadataScopedLister struct {
	indexer cache.Indexer
}

// List lists all Metadatas in the indexer for a workspace.
func (s *metadataScopedLister) List(selector labels.Selector) (ret []*tenancyv1alpha1.Metadata, err error) {
	err = cache.ListAll(s.indexer, selector, func(i interface{}) {
		ret = append(ret, i.(*tenancyv1alpha1.Metadata))
	})
	return ret, err
}

// Get retrieves the Metadata from the indexer for a given workspace and name.
func (s *metadataScopedLister) Get(name string) (*tenancyv1alpha1.Metadata, error) {
	key := name
	obj, exists, err := s.indexer.GetByKey(key)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(tenancyv1alpha1.Resource("Metadata"), name)
	}
	return obj.(*tenancyv1alpha1.Metadata), nil
}
