//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by kcp code-generator. DO NOT EDIT.

package v1alpha1

import (
	kcpcache "github.com/kcp-dev/apimachinery/v2/pkg/cache"
	"github.com/kcp-dev/logicalcluster/v3"

	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"

	tenancyv1alpha1 "github.com/faroshq/faros/pkg/apis/tenancy/v1alpha1"
)

// OrganizationClusterLister can list Organizations across all workspaces, or scope down to a OrganizationLister for one workspace.
// All objects returned here must be treated as read-only.
type OrganizationClusterLister interface {
	// List lists all Organizations in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*tenancyv1alpha1.Organization, err error)
	// Cluster returns a lister that can list and get Organizations in one workspace.
	Cluster(clusterName logicalcluster.Name) OrganizationLister
	OrganizationClusterListerExpansion
}

type organizationClusterLister struct {
	indexer cache.Indexer
}

// NewOrganizationClusterLister returns a new OrganizationClusterLister.
// We assume that the indexer:
// - is fed by a cross-workspace LIST+WATCH
// - uses kcpcache.MetaClusterNamespaceKeyFunc as the key function
// - has the kcpcache.ClusterIndex as an index
func NewOrganizationClusterLister(indexer cache.Indexer) *organizationClusterLister {
	return &organizationClusterLister{indexer: indexer}
}

// List lists all Organizations in the indexer across all workspaces.
func (s *organizationClusterLister) List(selector labels.Selector) (ret []*tenancyv1alpha1.Organization, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*tenancyv1alpha1.Organization))
	})
	return ret, err
}

// Cluster scopes the lister to one workspace, allowing users to list and get Organizations.
func (s *organizationClusterLister) Cluster(clusterName logicalcluster.Name) OrganizationLister {
	return &organizationLister{indexer: s.indexer, clusterName: clusterName}
}

// OrganizationLister can list all Organizations, or get one in particular.
// All objects returned here must be treated as read-only.
type OrganizationLister interface {
	// List lists all Organizations in the workspace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*tenancyv1alpha1.Organization, err error)
	// Get retrieves the Organization from the indexer for a given workspace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*tenancyv1alpha1.Organization, error)
	OrganizationListerExpansion
}

// organizationLister can list all Organizations inside a workspace.
type organizationLister struct {
	indexer     cache.Indexer
	clusterName logicalcluster.Name
}

// List lists all Organizations in the indexer for a workspace.
func (s *organizationLister) List(selector labels.Selector) (ret []*tenancyv1alpha1.Organization, err error) {
	err = kcpcache.ListAllByCluster(s.indexer, s.clusterName, selector, func(i interface{}) {
		ret = append(ret, i.(*tenancyv1alpha1.Organization))
	})
	return ret, err
}

// Get retrieves the Organization from the indexer for a given workspace and name.
func (s *organizationLister) Get(name string) (*tenancyv1alpha1.Organization, error) {
	key := kcpcache.ToClusterAwareKey(s.clusterName.String(), "", name)
	obj, exists, err := s.indexer.GetByKey(key)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(tenancyv1alpha1.Resource("Organization"), name)
	}
	return obj.(*tenancyv1alpha1.Organization), nil
}

// NewOrganizationLister returns a new OrganizationLister.
// We assume that the indexer:
// - is fed by a workspace-scoped LIST+WATCH
// - uses cache.MetaNamespaceKeyFunc as the key function
func NewOrganizationLister(indexer cache.Indexer) *organizationScopedLister {
	return &organizationScopedLister{indexer: indexer}
}

// organizationScopedLister can list all Organizations inside a workspace.
type organizationScopedLister struct {
	indexer cache.Indexer
}

// List lists all Organizations in the indexer for a workspace.
func (s *organizationScopedLister) List(selector labels.Selector) (ret []*tenancyv1alpha1.Organization, err error) {
	err = cache.ListAll(s.indexer, selector, func(i interface{}) {
		ret = append(ret, i.(*tenancyv1alpha1.Organization))
	})
	return ret, err
}

// Get retrieves the Organization from the indexer for a given workspace and name.
func (s *organizationScopedLister) Get(name string) (*tenancyv1alpha1.Organization, error) {
	key := name
	obj, exists, err := s.indexer.GetByKey(key)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(tenancyv1alpha1.Resource("Organization"), name)
	}
	return obj.(*tenancyv1alpha1.Organization), nil
}
