{{- if .Values.agent.hub.token }}
apiVersion: v1
kind: Secret
metadata:
  name: faros-agent-{{ .Values.agent.edgeName }}-kubeconfig
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "faros-agent.labels" . | nindent 4 }}
type: Opaque
data: {}
{{- end }}
