apiVersion: apis.kcp.io/v1alpha2
kind: APIExport
metadata:
  name: deployments.faros.sh
spec:
  resources:
  - group: deployments.faros.sh
    name: deployments
    schema: v260818-a3192d4d.deployments.deployments.faros.sh
    storage:
      crd: {}
  - group: deployments.faros.sh
    name: releases
    schema: v260818-a3192d4d.releases.deployments.faros.sh
    storage:
      crd: {}
  - group: deployments.faros.sh
    name: repositorysyncs
    schema: v260818-a3192d4d.repositorysyncs.deployments.faros.sh
    storage:
      crd: {}
status: {}
