apiVersion: apis.kcp.io/v1alpha2
kind: APIExport
metadata:
  name: code.faros.sh
spec:
  resources:
  - group: code.faros.sh
    name: changerequests
    schema: v260818-a3192d4d.changerequests.code.faros.sh
    storage:
      crd: {}
  - group: code.faros.sh
    name: collaborators
    schema: v260818-a3192d4d.collaborators.code.faros.sh
    storage:
      crd: {}
  - group: code.faros.sh
    name: connections
    schema: v260818-a3192d4d.connections.code.faros.sh
    storage:
      crd: {}
  - group: code.faros.sh
    name: deploykeys
    schema: v260818-a3192d4d.deploykeys.code.faros.sh
    storage:
      crd: {}
  - group: code.faros.sh
    name: packages
    schema: v260818-a3192d4d.packages.code.faros.sh
    storage:
      crd: {}
  - group: code.faros.sh
    name: repositories
    schema: v260818-a3192d4d.repositories.code.faros.sh
    storage:
      crd: {}
  - group: code.faros.sh
    name: repositorybuildstatuses
    schema: v260818-a3192d4d.repositorybuildstatuses.code.faros.sh
    storage:
      crd: {}
  - group: code.faros.sh
    name: repositorycheckouts
    schema: v260818-a3192d4d.repositorycheckouts.code.faros.sh
    storage:
      crd: {}
  - group: code.faros.sh
    name: repositorycommits
    schema: v260818-a3192d4d.repositorycommits.code.faros.sh
    storage:
      crd: {}
status: {}
