/*
Copyright 2026 The Faros Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Command telemetry-codegen validates and materializes the checked-in Faros
// telemetry catalog. Provider event roots are explicit inputs, while metrics
// remain centralized under telemetry/metrics.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"unicode"

	"github.com/faroshq/faros/telemetry/catalog"
)

const generatedHeader = `// Code generated by hack/telemetry-codegen; DO NOT EDIT.
//
// Copyright 2026 The Faros Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

`

type registryDocument struct {
	Events  []catalog.EventDefinition  `json:"events"`
	Metrics []catalog.MetricDefinition `json:"metrics"`
}

func main() {
	eventsDir := flag.String("events", "", "comma-separated event roots (default: telemetry/events plus providers/*/telemetry/events)")
	metricsDir := flag.String("metrics", "telemetry/metrics", "central metric definition directory")
	schemaDir := flag.String("schemas", "telemetry/schema", "JSON Schema directory")
	outputDir := flag.String("output", "telemetry/generated", "generated output directory")
	verify := flag.Bool("verify", false, "verify generated files instead of writing them")
	flag.Parse()

	if err := run(*eventsDir, *metricsDir, *schemaDir, *outputDir, *verify); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run(eventsDir, metricsDir, schemaDir, outputDir string, verify bool) error {
	eventDirs := splitPaths(eventsDir)
	if len(eventDirs) == 0 {
		var err error
		eventDirs, err = discoverEventDirs("telemetry/events", "providers")
		if err != nil {
			return fmt.Errorf("discover telemetry event roots: %w", err)
		}
	}
	if len(eventDirs) == 0 {
		return fmt.Errorf("load telemetry catalog: at least one event root is required")
	}
	registry, err := catalog.LoadWithEventDirs(eventDirs, metricsDir, schemaDir)
	if err != nil {
		return fmt.Errorf("load telemetry catalog: %w", err)
	}
	goSource, err := renderGo(registry)
	if err != nil {
		return fmt.Errorf("render generated registry: %w", err)
	}
	doc := renderMarkdown(registry)
	outputs := map[string][]byte{
		filepath.Join(outputDir, "registry.go"): goSource,
		filepath.Join(outputDir, "catalog.md"):  []byte(doc),
	}
	if verify {
		return verifyOutputs(outputs)
	}
	if err := os.MkdirAll(outputDir, 0o755); err != nil {
		return fmt.Errorf("create output directory %s: %w", outputDir, err)
	}
	paths := make([]string, 0, len(outputs))
	for path := range outputs {
		paths = append(paths, path)
	}
	sort.Strings(paths)
	for _, path := range paths {
		if err := os.WriteFile(path, outputs[path], 0o644); err != nil {
			return fmt.Errorf("write %s: %w", path, err)
		}
	}
	return nil
}

func splitPaths(value string) []string {
	parts := strings.Split(value, ",")
	paths := make([]string, 0, len(parts))
	seen := make(map[string]struct{}, len(parts))
	for _, part := range parts {
		part = strings.TrimSpace(part)
		if part == "" {
			continue
		}
		if _, exists := seen[part]; exists {
			continue
		}
		seen[part] = struct{}{}
		paths = append(paths, part)
	}
	return paths
}

// discoverEventDirs finds the platform root and every provider-owned event
// root. os.ReadDir returns entries in filename order, so the resulting roots
// and generated output remain deterministic as providers are added or removed.
func discoverEventDirs(platformDir, providersDir string) ([]string, error) {
	platformInfo, err := os.Stat(platformDir)
	if err != nil {
		return nil, err
	}
	if !platformInfo.IsDir() {
		return nil, fmt.Errorf("platform event root %s is not a directory", platformDir)
	}
	roots := []string{platformDir}
	entries, err := os.ReadDir(providersDir)
	if err != nil {
		return nil, err
	}
	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}
		root := filepath.Join(providersDir, entry.Name(), "telemetry", "events")
		info, err := os.Stat(root)
		if os.IsNotExist(err) {
			continue
		}
		if err != nil {
			return nil, err
		}
		if info.IsDir() {
			roots = append(roots, root)
		}
	}
	return roots, nil
}

func renderGo(registry catalog.Registry) ([]byte, error) {
	document, err := json.MarshalIndent(registryDocument{Events: registry.Events, Metrics: registry.Metrics}, "", "  ")
	if err != nil {
		return nil, err
	}
	encoded, err := json.Marshal(string(document))
	if err != nil {
		return nil, err
	}

	events := append([]catalog.EventDefinition(nil), registry.Events...)
	sort.Slice(events, func(i, j int) bool { return events[i].Action < events[j].Action })
	identifiers := make(map[string]string, len(events))
	for _, event := range events {
		identifier := actionIdentifier(event.Action)
		if previous, exists := identifiers[identifier]; exists && previous != event.Action {
			return nil, fmt.Errorf("event actions %q and %q collide as Go identifier %s", previous, event.Action, identifier)
		}
		identifiers[identifier] = event.Action
	}

	var source strings.Builder
	source.WriteString(generatedHeader)
	source.WriteString("package generated\n\n")
	source.WriteString("import (\n\t\"encoding/json\"\n\n\t\"github.com/faroshq/faros/telemetry/catalog\"\n)\n\n")
	fmt.Fprintf(&source, "var catalogJSON = []byte(%s)\n\n", string(encoded))
	source.WriteString(`type registryDocument struct {
	Events  []catalog.EventDefinition  ` + "`json:\"events\"`" + `
	Metrics []catalog.MetricDefinition ` + "`json:\"metrics\"`" + `
}

`)
	source.WriteString("// Action constants are generated from telemetry/events and provider-owned event roots.\n")
	source.WriteString("const (\n")
	for _, event := range events {
		fmt.Fprintf(&source, "\tAction%s = %q\n", actionIdentifier(event.Action), event.Action)
	}
	source.WriteString(")\n\n")
	source.WriteString("// ActionNames is the deterministic list of declared event actions.\n")
	source.WriteString("var ActionNames = []string{\n")
	for _, event := range events {
		fmt.Fprintf(&source, "\tAction%s,\n", actionIdentifier(event.Action))
	}
	source.WriteString("}\n\n")
	source.WriteString(`// MustRegistry returns the validated catalog embedded at code-generation time.
func MustRegistry() catalog.Registry {
	var document registryDocument
	if err := json.Unmarshal(catalogJSON, &document); err != nil {
		panic(err)
	}
	return catalog.Registry{Events: document.Events, Metrics: document.Metrics}
}

// EventRegistry indexes event definitions by their generated action name.
var EventRegistry = buildEventRegistry()

// MetricRegistry indexes metric definitions by key_path.
var MetricRegistry = buildMetricRegistry()

func buildEventRegistry() map[string]catalog.EventDefinition {
	registry := MustRegistry()
	result := make(map[string]catalog.EventDefinition, len(registry.Events))
	for _, event := range registry.Events {
		result[event.Action] = event
	}
	return result
}

func buildMetricRegistry() map[string]catalog.MetricDefinition {
	registry := MustRegistry()
	result := make(map[string]catalog.MetricDefinition, len(registry.Metrics))
	for _, metric := range registry.Metrics {
		result[metric.KeyPath] = metric
	}
	return result
}

// LookupEvent returns a generated event definition when action is declared.
func LookupEvent(action string) (catalog.EventDefinition, bool) {
	event, ok := EventRegistry[action]
	return event, ok
}

`)
	formatted, err := format.Source([]byte(source.String()))
	if err != nil {
		return nil, err
	}
	return formatted, nil
}

func actionIdentifier(action string) string {
	var b strings.Builder
	upper := true
	for _, r := range action {
		if r == '_' || r == '-' {
			upper = true
			continue
		}
		if upper {
			b.WriteRune(unicode.ToUpper(r))
			upper = false
		} else {
			b.WriteRune(r)
		}
	}
	return b.String()
}

func renderMarkdown(registry catalog.Registry) string {
	var b strings.Builder
	b.WriteString("# Faros telemetry catalog\n\n")
	b.WriteString("This file is generated from platform/provider event roots, central metrics, and the checked-in JSON Schemas.\n\n")
	b.WriteString("## Events\n\n")
	b.WriteString("| Action | Owner | Source | Product group | Categories | Lifecycle | Tiers | Identifiers | Privacy | Retention | Properties |\n")
	b.WriteString("| --- | --- | --- | --- | --- | --- | --- | --- | --- | ---: | --- |\n")
	events := append([]catalog.EventDefinition(nil), registry.Events...)
	sort.Slice(events, func(i, j int) bool {
		if events[i].SourcePath == events[j].SourcePath {
			return events[i].Action < events[j].Action
		}
		return events[i].SourcePath < events[j].SourcePath
	})
	for _, event := range events {
		properties := make([]string, 0, len(event.AdditionalProperties))
		for name, property := range event.AdditionalProperties {
			values := ""
			if len(property.Enum) > 0 {
				values = "=" + strings.Join(property.Enum, ",")
			}
			properties = append(properties, fmt.Sprintf("%s (%s)%s", name, property.Type, values))
		}
		sort.Strings(properties)
		lifecycle := event.Status
		if event.Milestone != "" {
			lifecycle += " @ " + event.Milestone
		}
		privacy := event.Privacy.Class + "; pseudonymize=" + strings.Join(event.Privacy.Pseudonymize, ",")
		if event.Privacy.NoRawContent {
			privacy += "; no_raw_content"
		}
		fmt.Fprintf(&b, "| `%s` | %s | `%s` | %s | %s | %s | %s | %s | %s | %d | %s |\n",
			markdownCell(event.Action), markdownCell(event.Owner), markdownCell(event.SourcePath), markdownCell(event.ProductGroup),
			markdownCell(strings.Join(event.ProductCategories, ", ")), markdownCell(lifecycle), markdownCell(strings.Join(event.Tiers, ", ")),
			markdownCell(strings.Join(event.Identifiers, ", ")), markdownCell(privacy), event.RetentionDays, markdownCell(strings.Join(properties, ", ")))
	}
	b.WriteString("\n## Metrics and funnels\n\n")
	b.WriteString("| Key path | Kind | Owner | Source | Description | Events | Labels |\n")
	b.WriteString("| --- | --- | --- | --- | --- | --- | --- |\n")
	metrics := append([]catalog.MetricDefinition(nil), registry.Metrics...)
	sort.Slice(metrics, func(i, j int) bool { return metrics[i].KeyPath < metrics[j].KeyPath })
	for _, metric := range metrics {
		events := make([]string, 0, len(metric.Events))
		for _, selection := range metric.Events {
			step := selection.Name
			if selection.Unique != "" {
				step += " [unique " + selection.Unique + "]"
			}
			if len(selection.Filter) > 0 {
				filters := make([]string, 0, len(selection.Filter))
				for name, value := range selection.Filter {
					filters = append(filters, name+"="+value)
				}
				sort.Strings(filters)
				step += " {" + strings.Join(filters, ", ") + "}"
			}
			events = append(events, step)
		}
		labels := make([]string, 0, len(metric.Labels))
		for name, label := range metric.Labels {
			labels = append(labels, name+"="+strings.Join(label.Values, ","))
		}
		sort.Strings(labels)
		fmt.Fprintf(&b, "| `%s` | %s | %s | `%s` | %s | %s | %s |\n",
			markdownCell(metric.KeyPath), markdownCell(metric.MetricKind), markdownCell(metric.Owner), markdownCell(metric.SourcePath),
			markdownCell(metric.Description), markdownCell(strings.Join(events, "; ")), markdownCell(strings.Join(labels, "; ")))
	}
	return b.String()
}

func markdownCell(value string) string {
	value = strings.ReplaceAll(value, "|", `\|`)
	value = strings.ReplaceAll(value, "\r", " ")
	return strings.ReplaceAll(value, "\n", " ")
}

func verifyOutputs(outputs map[string][]byte) error {
	paths := make([]string, 0, len(outputs))
	for path := range outputs {
		paths = append(paths, path)
	}
	sort.Strings(paths)
	for _, path := range paths {
		actual, err := os.ReadFile(path)
		if err != nil {
			return fmt.Errorf("read generated output %s: %w", path, err)
		}
		if string(actual) != string(outputs[path]) {
			return fmt.Errorf("generated output %s is stale; run make telemetry-codegen", path)
		}
	}
	return nil
}
