apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: faros-operator
  name: faros-operator
  namespace: faros-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: faros-operator
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: faros-operator
    spec:
      containers:
      - command:
        - faros
        args:
        - operator
        image: GENERATED
        name: faros-operator
        ports:
        - containerPort: 8080
          name: http
      nodeSelector:
        node-role.kubernetes.io/master: ""
      serviceAccountName: faros-operator
      priorityClassName: system-cluster-critical
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
