apiVersion: apis.kcp.io/v1alpha2
kind: APIExport
metadata:
  name: linear.providers.faros.sh
spec:
  resources:
  - group: linear.providers.faros.sh
    name: connections
    schema: v260914-83a64688.connections.linear.providers.faros.sh
    storage:
      crd: {}
  - group: linear.providers.faros.sh
    name: teams
    schema: v260913-c4007149.teams.linear.providers.faros.sh
    storage:
      crd: {}
status: {}
