apiVersion: apis.kcp.io/v1alpha2
kind: APIExport
metadata:
  name: secrets.faros.sh
spec:
  resources:
  - group: secrets.faros.sh
    name: secretstores
    schema: v260817-6b19c407.secretstores.secrets.faros.sh
    storage:
      crd: {}
  - group: secrets.faros.sh
    name: syncedsecrets
    schema: v260817-6b19c407.syncedsecrets.secrets.faros.sh
    storage:
      crd: {}
status: {}
