/* tslint:disable */
/* eslint-disable */
/**
 * Faros
 * Resource for managing Faros workspaces
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mangirdas@judeikis.LT
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { OidcIDToken } from './OidcIDToken';
import {
    OidcIDTokenFromJSON,
    OidcIDTokenFromJSONTyped,
    OidcIDTokenToJSON,
} from './OidcIDToken';

/**
 * 
 * @export
 * @interface ModelsLoginResponse
 */
export interface ModelsLoginResponse {
    /**
     * 
     * @type {string}
     * @memberof ModelsLoginResponse
     */
    accessToken: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsLoginResponse
     */
    certificateAuthorityData: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsLoginResponse
     */
    email: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsLoginResponse
     */
    expiresAt: number;
    /**
     * 
     * @type {OidcIDToken}
     * @memberof ModelsLoginResponse
     */
    idToken: OidcIDToken;
    /**
     * 
     * @type {string}
     * @memberof ModelsLoginResponse
     */
    refreshToken: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsLoginResponse
     */
    serverBaseUrl: string;
}

/**
 * Check if a given object implements the ModelsLoginResponse interface.
 */
export function instanceOfModelsLoginResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "accessToken" in value;
    isInstance = isInstance && "certificateAuthorityData" in value;
    isInstance = isInstance && "email" in value;
    isInstance = isInstance && "expiresAt" in value;
    isInstance = isInstance && "idToken" in value;
    isInstance = isInstance && "refreshToken" in value;
    isInstance = isInstance && "serverBaseUrl" in value;

    return isInstance;
}

export function ModelsLoginResponseFromJSON(json: any): ModelsLoginResponse {
    return ModelsLoginResponseFromJSONTyped(json, false);
}

export function ModelsLoginResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsLoginResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accessToken': json['accessToken'],
        'certificateAuthorityData': json['certificateAuthorityData'],
        'email': json['email'],
        'expiresAt': json['expiresAt'],
        'idToken': OidcIDTokenFromJSON(json['idToken']),
        'refreshToken': json['refreshToken'],
        'serverBaseUrl': json['serverBaseUrl'],
    };
}

export function ModelsLoginResponseToJSON(value?: ModelsLoginResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'accessToken': value.accessToken,
        'certificateAuthorityData': value.certificateAuthorityData,
        'email': value.email,
        'expiresAt': value.expiresAt,
        'idToken': OidcIDTokenToJSON(value.idToken),
        'refreshToken': value.refreshToken,
        'serverBaseUrl': value.serverBaseUrl,
    };
}

