/* tslint:disable */
/* eslint-disable */
/**
 * Faros
 * Resource for managing Faros workspaces
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mangirdas@judeikis.LT
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OidcClaimSource
 */
export interface OidcClaimSource {
    /**
     * 
     * @type {string}
     * @memberof OidcClaimSource
     */
    accessToken: string;
    /**
     * 
     * @type {string}
     * @memberof OidcClaimSource
     */
    endpoint: string;
}

/**
 * Check if a given object implements the OidcClaimSource interface.
 */
export function instanceOfOidcClaimSource(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "accessToken" in value;
    isInstance = isInstance && "endpoint" in value;

    return isInstance;
}

export function OidcClaimSourceFromJSON(json: any): OidcClaimSource {
    return OidcClaimSourceFromJSONTyped(json, false);
}

export function OidcClaimSourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): OidcClaimSource {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accessToken': json['access_token'],
        'endpoint': json['endpoint'],
    };
}

export function OidcClaimSourceToJSON(value?: OidcClaimSource | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'access_token': value.accessToken,
        'endpoint': value.endpoint,
    };
}

