/* tslint:disable */
/* eslint-disable */
/**
 * Faros
 * Resource for managing Faros workspaces
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mangirdas@judeikis.LT
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { V1ObjectMeta } from './V1ObjectMeta';
import {
    V1ObjectMetaFromJSON,
    V1ObjectMetaFromJSONTyped,
    V1ObjectMetaToJSON,
} from './V1ObjectMeta';
import type { V1alpha1OrganizationSpec } from './V1alpha1OrganizationSpec';
import {
    V1alpha1OrganizationSpecFromJSON,
    V1alpha1OrganizationSpecFromJSONTyped,
    V1alpha1OrganizationSpecToJSON,
} from './V1alpha1OrganizationSpec';
import type { V1alpha1OrganizationStatus } from './V1alpha1OrganizationStatus';
import {
    V1alpha1OrganizationStatusFromJSON,
    V1alpha1OrganizationStatusFromJSONTyped,
    V1alpha1OrganizationStatusToJSON,
} from './V1alpha1OrganizationStatus';

/**
 * 
 * @export
 * @interface V1alpha1Organization
 */
export interface V1alpha1Organization {
    /**
     * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
     * @type {string}
     * @memberof V1alpha1Organization
     */
    apiVersion?: string;
    /**
     * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
     * @type {string}
     * @memberof V1alpha1Organization
     */
    kind?: string;
    /**
     * 
     * @type {V1ObjectMeta}
     * @memberof V1alpha1Organization
     */
    metadata?: V1ObjectMeta;
    /**
     * 
     * @type {V1alpha1OrganizationSpec}
     * @memberof V1alpha1Organization
     */
    spec?: V1alpha1OrganizationSpec;
    /**
     * 
     * @type {V1alpha1OrganizationStatus}
     * @memberof V1alpha1Organization
     */
    status?: V1alpha1OrganizationStatus;
}

/**
 * Check if a given object implements the V1alpha1Organization interface.
 */
export function instanceOfV1alpha1Organization(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function V1alpha1OrganizationFromJSON(json: any): V1alpha1Organization {
    return V1alpha1OrganizationFromJSONTyped(json, false);
}

export function V1alpha1OrganizationFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1alpha1Organization {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'apiVersion': !exists(json, 'apiVersion') ? undefined : json['apiVersion'],
        'kind': !exists(json, 'kind') ? undefined : json['kind'],
        'metadata': !exists(json, 'metadata') ? undefined : V1ObjectMetaFromJSON(json['metadata']),
        'spec': !exists(json, 'spec') ? undefined : V1alpha1OrganizationSpecFromJSON(json['spec']),
        'status': !exists(json, 'status') ? undefined : V1alpha1OrganizationStatusFromJSON(json['status']),
    };
}

export function V1alpha1OrganizationToJSON(value?: V1alpha1Organization | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'apiVersion': value.apiVersion,
        'kind': value.kind,
        'metadata': V1ObjectMetaToJSON(value.metadata),
        'spec': V1alpha1OrganizationSpecToJSON(value.spec),
        'status': V1alpha1OrganizationStatusToJSON(value.status),
    };
}

