/* tslint:disable */
/* eslint-disable */
/**
 * Faros
 * Resource for managing Faros workspaces
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mangirdas@judeikis.LT
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { V1alpha1ObjectReference } from './V1alpha1ObjectReference';
import {
    V1alpha1ObjectReferenceFromJSON,
    V1alpha1ObjectReferenceFromJSONTyped,
    V1alpha1ObjectReferenceToJSON,
} from './V1alpha1ObjectReference';

/**
 * 
 * @export
 * @interface V1alpha1OrganizationSpec
 */
export interface V1alpha1OrganizationSpec {
    /**
     * 
     * @type {string}
     * @memberof V1alpha1OrganizationSpec
     */
    description?: string;
    /**
     * 
     * @type {Array<V1alpha1ObjectReference>}
     * @memberof V1alpha1OrganizationSpec
     */
    ownersRef?: Array<V1alpha1ObjectReference>;
}

/**
 * Check if a given object implements the V1alpha1OrganizationSpec interface.
 */
export function instanceOfV1alpha1OrganizationSpec(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function V1alpha1OrganizationSpecFromJSON(json: any): V1alpha1OrganizationSpec {
    return V1alpha1OrganizationSpecFromJSONTyped(json, false);
}

export function V1alpha1OrganizationSpecFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1alpha1OrganizationSpec {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': !exists(json, 'description') ? undefined : json['description'],
        'ownersRef': !exists(json, 'ownersRef') ? undefined : ((json['ownersRef'] as Array<any>).map(V1alpha1ObjectReferenceFromJSON)),
    };
}

export function V1alpha1OrganizationSpecToJSON(value?: V1alpha1OrganizationSpec | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': value.description,
        'ownersRef': value.ownersRef === undefined ? undefined : ((value.ownersRef as Array<any>).map(V1alpha1ObjectReferenceToJSON)),
    };
}

