/* tslint:disable */
/* eslint-disable */
/**
 * Faros
 * Resource for managing Faros workspaces
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mangirdas@judeikis.LT
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1alpha1ObjectReference
 */
export interface V1alpha1ObjectReference {
    /**
     * 
     * @type {string}
     * @memberof V1alpha1ObjectReference
     */
    apiVersion?: string;
    /**
     * 
     * @type {string}
     * @memberof V1alpha1ObjectReference
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof V1alpha1ObjectReference
     */
    kind?: string;
    /**
     * 
     * @type {string}
     * @memberof V1alpha1ObjectReference
     */
    name?: string;
}

/**
 * Check if a given object implements the V1alpha1ObjectReference interface.
 */
export function instanceOfV1alpha1ObjectReference(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function V1alpha1ObjectReferenceFromJSON(json: any): V1alpha1ObjectReference {
    return V1alpha1ObjectReferenceFromJSONTyped(json, false);
}

export function V1alpha1ObjectReferenceFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1alpha1ObjectReference {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'apiVersion': !exists(json, 'apiVersion') ? undefined : json['apiVersion'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'kind': !exists(json, 'kind') ? undefined : json['kind'],
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function V1alpha1ObjectReferenceToJSON(value?: V1alpha1ObjectReference | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'apiVersion': value.apiVersion,
        'email': value.email,
        'kind': value.kind,
        'name': value.name,
    };
}

