/* tslint:disable */
/* eslint-disable */
/**
 * Faros
 * Resource for managing Faros workspaces
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mangirdas@judeikis.LT
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { V1alpha1Condition } from './V1alpha1Condition';
import {
    V1alpha1ConditionFromJSON,
    V1alpha1ConditionFromJSONTyped,
    V1alpha1ConditionToJSON,
} from './V1alpha1Condition';

/**
 * 
 * @export
 * @interface V1alpha1OrganizationStatus
 */
export interface V1alpha1OrganizationStatus {
    /**
     * 
     * @type {Array<V1alpha1Condition>}
     * @memberof V1alpha1OrganizationStatus
     */
    conditions?: Array<V1alpha1Condition>;
    /**
     * 
     * @type {string}
     * @memberof V1alpha1OrganizationStatus
     */
    workspaceURL?: string;
}

/**
 * Check if a given object implements the V1alpha1OrganizationStatus interface.
 */
export function instanceOfV1alpha1OrganizationStatus(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function V1alpha1OrganizationStatusFromJSON(json: any): V1alpha1OrganizationStatus {
    return V1alpha1OrganizationStatusFromJSONTyped(json, false);
}

export function V1alpha1OrganizationStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1alpha1OrganizationStatus {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'conditions': !exists(json, 'conditions') ? undefined : ((json['conditions'] as Array<any>).map(V1alpha1ConditionFromJSON)),
        'workspaceURL': !exists(json, 'workspaceURL') ? undefined : json['workspaceURL'],
    };
}

export function V1alpha1OrganizationStatusToJSON(value?: V1alpha1OrganizationStatus | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'conditions': value.conditions === undefined ? undefined : ((value.conditions as Array<any>).map(V1alpha1ConditionToJSON)),
        'workspaceURL': value.workspaceURL,
    };
}

