/* tslint:disable */
/* eslint-disable */
/**
 * Faros
 * Resource for managing Faros workspaces
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mangirdas@judeikis.LT
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * TypeMeta describes an individual object in an API response or request with strings representing the type of the object and its API schema version. Structures that are versioned or persisted should inline TypeMeta.
 * @export
 * @interface V1TypeMeta
 */
export interface V1TypeMeta {
    /**
     * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
     * @type {string}
     * @memberof V1TypeMeta
     */
    apiVersion?: string;
    /**
     * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
     * @type {string}
     * @memberof V1TypeMeta
     */
    kind?: string;
}

/**
 * Check if a given object implements the V1TypeMeta interface.
 */
export function instanceOfV1TypeMeta(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function V1TypeMetaFromJSON(json: any): V1TypeMeta {
    return V1TypeMetaFromJSONTyped(json, false);
}

export function V1TypeMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1TypeMeta {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'apiVersion': !exists(json, 'apiVersion') ? undefined : json['apiVersion'],
        'kind': !exists(json, 'kind') ? undefined : json['kind'],
    };
}

export function V1TypeMetaToJSON(value?: V1TypeMeta | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'apiVersion': value.apiVersion,
        'kind': value.kind,
    };
}

