//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by kcp code-generator. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	kcpcache "github.com/kcp-dev/apimachinery/v2/pkg/cache"
	kcpinformers "github.com/kcp-dev/apimachinery/v2/third_party/informers"
	"github.com/kcp-dev/logicalcluster/v3"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/watch"
	"k8s.io/client-go/tools/cache"

	tenancyv1alpha1 "github.com/faroshq/faros/pkg/apis/tenancy/v1alpha1"
	scopedclientset "github.com/faroshq/faros/pkg/client/clientset/versioned"
	clientset "github.com/faroshq/faros/pkg/client/clientset/versioned/cluster"
	"github.com/faroshq/faros/pkg/client/informers/externalversions/internalinterfaces"
	tenancyv1alpha1listers "github.com/faroshq/faros/pkg/client/listers/tenancy/v1alpha1"
)

// MetadataClusterInformer provides access to a shared informer and lister for
// Metadatas.
type MetadataClusterInformer interface {
	Cluster(logicalcluster.Name) MetadataInformer
	Informer() kcpcache.ScopeableSharedIndexInformer
	Lister() tenancyv1alpha1listers.MetadataClusterLister
}

type metadataClusterInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewMetadataClusterInformer constructs a new informer for Metadata type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewMetadataClusterInformer(client clientset.ClusterInterface, resyncPeriod time.Duration, indexers cache.Indexers) kcpcache.ScopeableSharedIndexInformer {
	return NewFilteredMetadataClusterInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredMetadataClusterInformer constructs a new informer for Metadata type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredMetadataClusterInformer(client clientset.ClusterInterface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) kcpcache.ScopeableSharedIndexInformer {
	return kcpinformers.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.TenancyV1alpha1().Metadatas().List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.TenancyV1alpha1().Metadatas().Watch(context.TODO(), options)
			},
		},
		&tenancyv1alpha1.Metadata{},
		resyncPeriod,
		indexers,
	)
}

func (f *metadataClusterInformer) defaultInformer(client clientset.ClusterInterface, resyncPeriod time.Duration) kcpcache.ScopeableSharedIndexInformer {
	return NewFilteredMetadataClusterInformer(client, resyncPeriod, cache.Indexers{
		kcpcache.ClusterIndexName: kcpcache.ClusterIndexFunc,
	},
		f.tweakListOptions,
	)
}

func (f *metadataClusterInformer) Informer() kcpcache.ScopeableSharedIndexInformer {
	return f.factory.InformerFor(&tenancyv1alpha1.Metadata{}, f.defaultInformer)
}

func (f *metadataClusterInformer) Lister() tenancyv1alpha1listers.MetadataClusterLister {
	return tenancyv1alpha1listers.NewMetadataClusterLister(f.Informer().GetIndexer())
}

// MetadataInformer provides access to a shared informer and lister for
// Metadatas.
type MetadataInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() tenancyv1alpha1listers.MetadataLister
}

func (f *metadataClusterInformer) Cluster(clusterName logicalcluster.Name) MetadataInformer {
	return &metadataInformer{
		informer: f.Informer().Cluster(clusterName),
		lister:   f.Lister().Cluster(clusterName),
	}
}

type metadataInformer struct {
	informer cache.SharedIndexInformer
	lister   tenancyv1alpha1listers.MetadataLister
}

func (f *metadataInformer) Informer() cache.SharedIndexInformer {
	return f.informer
}

func (f *metadataInformer) Lister() tenancyv1alpha1listers.MetadataLister {
	return f.lister
}

type metadataScopedInformer struct {
	factory          internalinterfaces.SharedScopedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

func (f *metadataScopedInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&tenancyv1alpha1.Metadata{}, f.defaultInformer)
}

func (f *metadataScopedInformer) Lister() tenancyv1alpha1listers.MetadataLister {
	return tenancyv1alpha1listers.NewMetadataLister(f.Informer().GetIndexer())
}

// NewMetadataInformer constructs a new informer for Metadata type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewMetadataInformer(client scopedclientset.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredMetadataInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredMetadataInformer constructs a new informer for Metadata type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredMetadataInformer(client scopedclientset.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.TenancyV1alpha1().Metadatas().List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.TenancyV1alpha1().Metadatas().Watch(context.TODO(), options)
			},
		},
		&tenancyv1alpha1.Metadata{},
		resyncPeriod,
		indexers,
	)
}

func (f *metadataScopedInformer) defaultInformer(client scopedclientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredMetadataInformer(client, resyncPeriod, cache.Indexers{}, f.tweakListOptions)
}
