//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by kcp code-generator. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/watch"
	"k8s.io/client-go/tools/cache"

	kcpcache "github.com/kcp-dev/apimachinery/v2/pkg/cache"
	kcpinformers "github.com/kcp-dev/apimachinery/v2/third_party/informers"
	"github.com/kcp-dev/logicalcluster/v3"

	tenancyv1alpha1 "github.com/faroshq/faros/pkg/apis/tenancy/v1alpha1"
	scopedclientset "github.com/faroshq/faros/pkg/client/clientset/versioned"
	clientset "github.com/faroshq/faros/pkg/client/clientset/versioned/cluster"
	"github.com/faroshq/faros/pkg/client/informers/externalversions/internalinterfaces"
	tenancyv1alpha1listers "github.com/faroshq/faros/pkg/client/listers/tenancy/v1alpha1"
)

// OrganizationClusterInformer provides access to a shared informer and lister for
// Organizations.
type OrganizationClusterInformer interface {
	Cluster(logicalcluster.Name) OrganizationInformer
	Informer() kcpcache.ScopeableSharedIndexInformer
	Lister() tenancyv1alpha1listers.OrganizationClusterLister
}

type organizationClusterInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewOrganizationClusterInformer constructs a new informer for Organization type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewOrganizationClusterInformer(client clientset.ClusterInterface, resyncPeriod time.Duration, indexers cache.Indexers) kcpcache.ScopeableSharedIndexInformer {
	return NewFilteredOrganizationClusterInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredOrganizationClusterInformer constructs a new informer for Organization type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredOrganizationClusterInformer(client clientset.ClusterInterface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) kcpcache.ScopeableSharedIndexInformer {
	return kcpinformers.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.TenancyV1alpha1().Organizations().List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.TenancyV1alpha1().Organizations().Watch(context.TODO(), options)
			},
		},
		&tenancyv1alpha1.Organization{},
		resyncPeriod,
		indexers,
	)
}

func (f *organizationClusterInformer) defaultInformer(client clientset.ClusterInterface, resyncPeriod time.Duration) kcpcache.ScopeableSharedIndexInformer {
	return NewFilteredOrganizationClusterInformer(client, resyncPeriod, cache.Indexers{
		kcpcache.ClusterIndexName: kcpcache.ClusterIndexFunc,
	},
		f.tweakListOptions,
	)
}

func (f *organizationClusterInformer) Informer() kcpcache.ScopeableSharedIndexInformer {
	return f.factory.InformerFor(&tenancyv1alpha1.Organization{}, f.defaultInformer)
}

func (f *organizationClusterInformer) Lister() tenancyv1alpha1listers.OrganizationClusterLister {
	return tenancyv1alpha1listers.NewOrganizationClusterLister(f.Informer().GetIndexer())
}

// OrganizationInformer provides access to a shared informer and lister for
// Organizations.
type OrganizationInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() tenancyv1alpha1listers.OrganizationLister
}

func (f *organizationClusterInformer) Cluster(clusterName logicalcluster.Name) OrganizationInformer {
	return &organizationInformer{
		informer: f.Informer().Cluster(clusterName),
		lister:   f.Lister().Cluster(clusterName),
	}
}

type organizationInformer struct {
	informer cache.SharedIndexInformer
	lister   tenancyv1alpha1listers.OrganizationLister
}

func (f *organizationInformer) Informer() cache.SharedIndexInformer {
	return f.informer
}

func (f *organizationInformer) Lister() tenancyv1alpha1listers.OrganizationLister {
	return f.lister
}

type organizationScopedInformer struct {
	factory          internalinterfaces.SharedScopedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

func (f *organizationScopedInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&tenancyv1alpha1.Organization{}, f.defaultInformer)
}

func (f *organizationScopedInformer) Lister() tenancyv1alpha1listers.OrganizationLister {
	return tenancyv1alpha1listers.NewOrganizationLister(f.Informer().GetIndexer())
}

// NewOrganizationInformer constructs a new informer for Organization type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewOrganizationInformer(client scopedclientset.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredOrganizationInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredOrganizationInformer constructs a new informer for Organization type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredOrganizationInformer(client scopedclientset.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.TenancyV1alpha1().Organizations().List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.TenancyV1alpha1().Organizations().Watch(context.TODO(), options)
			},
		},
		&tenancyv1alpha1.Organization{},
		resyncPeriod,
		indexers,
	)
}

func (f *organizationScopedInformer) defaultInformer(client scopedclientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredOrganizationInformer(client, resyncPeriod, cache.Indexers{}, f.tweakListOptions)
}
