apiVersion: linear.providers.faros.sh/v1alpha1
kind: Connection
metadata:
  name: linear
spec:
  apiKeySecretRef:
    namespace: default
    name: linear-api
    key: apiKey
  teams:
    - id: REPLACE_WITH_TEAM_UUID
