// Copyright (c) Faros.sh
// Licensed under the Apache License 2.0.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/faroshq/faros/pkg/operator/apis/faros.sh/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeWorkers implements WorkerInterface
type FakeWorkers struct {
	Fake *FakeFarosV1alpha1
}

var workersResource = schema.GroupVersionResource{Group: "faros.sh", Version: "v1alpha1", Resource: "workers"}

var workersKind = schema.GroupVersionKind{Group: "faros.sh", Version: "v1alpha1", Kind: "Worker"}

// Get takes name of the worker, and returns the corresponding worker object, and an error if there is any.
func (c *FakeWorkers) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Worker, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(workersResource, name), &v1alpha1.Worker{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Worker), err
}

// List takes label and field selectors, and returns the list of Workers that match those selectors.
func (c *FakeWorkers) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.WorkerList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(workersResource, workersKind, opts), &v1alpha1.WorkerList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.WorkerList{ListMeta: obj.(*v1alpha1.WorkerList).ListMeta}
	for _, item := range obj.(*v1alpha1.WorkerList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested workers.
func (c *FakeWorkers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(workersResource, opts))
}

// Create takes the representation of a worker and creates it.  Returns the server's representation of the worker, and an error, if there is any.
func (c *FakeWorkers) Create(ctx context.Context, worker *v1alpha1.Worker, opts v1.CreateOptions) (result *v1alpha1.Worker, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(workersResource, worker), &v1alpha1.Worker{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Worker), err
}

// Update takes the representation of a worker and updates it. Returns the server's representation of the worker, and an error, if there is any.
func (c *FakeWorkers) Update(ctx context.Context, worker *v1alpha1.Worker, opts v1.UpdateOptions) (result *v1alpha1.Worker, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(workersResource, worker), &v1alpha1.Worker{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Worker), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeWorkers) UpdateStatus(ctx context.Context, worker *v1alpha1.Worker, opts v1.UpdateOptions) (*v1alpha1.Worker, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(workersResource, "status", worker), &v1alpha1.Worker{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Worker), err
}

// Delete takes name of the worker and deletes it. Returns an error if one occurs.
func (c *FakeWorkers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(workersResource, name), &v1alpha1.Worker{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeWorkers) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(workersResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.WorkerList{})
	return err
}

// Patch applies the patch and returns the patched worker.
func (c *FakeWorkers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Worker, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(workersResource, name, pt, data, subresources...), &v1alpha1.Worker{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Worker), err
}
