// Copyright (c) Faros.sh
// Licensed under the Apache License 2.0.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"

	v1alpha1 "github.com/faroshq/faros/pkg/operator/clientset/faros.sh/v1alpha1/versioned/typed/faros.sh/v1alpha1"
)

type FakeFarosV1alpha1 struct {
	*testing.Fake
}

func (c *FakeFarosV1alpha1) Clusters(namespace string) v1alpha1.ClusterInterface {
	return &FakeClusters{c, namespace}
}

func (c *FakeFarosV1alpha1) Configs() v1alpha1.ConfigInterface {
	return &FakeConfigs{c}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeFarosV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
