//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositorySync) DeepCopyInto(out *RepositorySync) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositorySync.
func (in *RepositorySync) DeepCopy() *RepositorySync {
	if in == nil {
		return nil
	}
	out := new(RepositorySync)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RepositorySync) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositorySyncInventoryItem) DeepCopyInto(out *RepositorySyncInventoryItem) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositorySyncInventoryItem.
func (in *RepositorySyncInventoryItem) DeepCopy() *RepositorySyncInventoryItem {
	if in == nil {
		return nil
	}
	out := new(RepositorySyncInventoryItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositorySyncList) DeepCopyInto(out *RepositorySyncList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RepositorySync, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositorySyncList.
func (in *RepositorySyncList) DeepCopy() *RepositorySyncList {
	if in == nil {
		return nil
	}
	out := new(RepositorySyncList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RepositorySyncList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositorySyncSpec) DeepCopyInto(out *RepositorySyncSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositorySyncSpec.
func (in *RepositorySyncSpec) DeepCopy() *RepositorySyncSpec {
	if in == nil {
		return nil
	}
	out := new(RepositorySyncSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositorySyncStatus) DeepCopyInto(out *RepositorySyncStatus) {
	*out = *in
	if in.Inventory != nil {
		in, out := &in.Inventory, &out.Inventory
		*out = make([]RepositorySyncInventoryItem, len(*in))
		copy(*out, *in)
	}
	if in.TargetRequirements != nil {
		in, out := &in.TargetRequirements, &out.TargetRequirements
		*out = make([]RepositorySyncTargetRequirement, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositorySyncStatus.
func (in *RepositorySyncStatus) DeepCopy() *RepositorySyncStatus {
	if in == nil {
		return nil
	}
	out := new(RepositorySyncStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositorySyncTargetClaim) DeepCopyInto(out *RepositorySyncTargetClaim) {
	*out = *in
	if in.Verbs != nil {
		in, out := &in.Verbs, &out.Verbs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositorySyncTargetClaim.
func (in *RepositorySyncTargetClaim) DeepCopy() *RepositorySyncTargetClaim {
	if in == nil {
		return nil
	}
	out := new(RepositorySyncTargetClaim)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositorySyncTargetRequirement) DeepCopyInto(out *RepositorySyncTargetRequirement) {
	*out = *in
	if in.Claim != nil {
		in, out := &in.Claim, &out.Claim
		*out = new(RepositorySyncTargetClaim)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositorySyncTargetRequirement.
func (in *RepositorySyncTargetRequirement) DeepCopy() *RepositorySyncTargetRequirement {
	if in == nil {
		return nil
	}
	out := new(RepositorySyncTargetRequirement)
	in.DeepCopyInto(out)
	return out
}
