apiVersion: apis.kcp.io/v1alpha2
kind: APIExport
metadata:
  name: providers.faros.sh
spec:
  resources:
  - group: providers.faros.sh
    name: catalogentries
    schema: v260817-6f7e8622.catalogentries.providers.faros.sh
    storage:
      crd: {}
status: {}
