/* tslint:disable */
/* eslint-disable */
/**
 * Faros
 * Resource for managing Faros workspaces
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mangirdas@judeikis.LT
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ModelsLoginResponse,
  V1alpha1Organization,
  V1alpha1OrganizationList,
  V1alpha1Workspace,
  V1alpha1WorkspaceList,
} from '../models';
import {
    ModelsLoginResponseFromJSON,
    ModelsLoginResponseToJSON,
    V1alpha1OrganizationFromJSON,
    V1alpha1OrganizationToJSON,
    V1alpha1OrganizationListFromJSON,
    V1alpha1OrganizationListToJSON,
    V1alpha1WorkspaceFromJSON,
    V1alpha1WorkspaceToJSON,
    V1alpha1WorkspaceListFromJSON,
    V1alpha1WorkspaceListToJSON,
} from '../models';

export interface CreateWorkspaceRequest {
    organization: string;
}

export interface DeleteOrganizationRequest {
    organization: string;
}

export interface DeleteWorkspaceRequest {
    workspace: string;
    organization: string;
}

export interface GetOrganizationRequest {
    organization: string;
}

export interface GetWorkspaceRequest {
    workspace: string;
    organization: string;
}

export interface ListWorkspacesRequest {
    organization: string;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Create organization
     */
    async createOrganizationRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V1alpha1Organization>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/faros.sh/api/v1alpha1/organizations`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => V1alpha1OrganizationFromJSON(jsonValue));
    }

    /**
     * Create organization
     */
    async createOrganization(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V1alpha1Organization> {
        const response = await this.createOrganizationRaw(initOverrides);
        return await response.value();
    }

    /**
     * Create workspace
     */
    async createWorkspaceRaw(requestParameters: CreateWorkspaceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V1alpha1Organization>> {
        if (requestParameters.organization === null || requestParameters.organization === undefined) {
            throw new runtime.RequiredError('organization','Required parameter requestParameters.organization was null or undefined when calling createWorkspace.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/faros.sh/api/v1alpha1/organizations/{organization}/workspaces`.replace(`{${"organization"}}`, encodeURIComponent(String(requestParameters.organization))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => V1alpha1OrganizationFromJSON(jsonValue));
    }

    /**
     * Create workspace
     */
    async createWorkspace(requestParameters: CreateWorkspaceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V1alpha1Organization> {
        const response = await this.createWorkspaceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete organization
     */
    async deleteOrganizationRaw(requestParameters: DeleteOrganizationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.organization === null || requestParameters.organization === undefined) {
            throw new runtime.RequiredError('organization','Required parameter requestParameters.organization was null or undefined when calling deleteOrganization.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/faros.sh/api/v1alpha1/organizations/{organization}`.replace(`{${"organization"}}`, encodeURIComponent(String(requestParameters.organization))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete organization
     */
    async deleteOrganization(requestParameters: DeleteOrganizationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteOrganizationRaw(requestParameters, initOverrides);
    }

    /**
     * Delete workspace
     */
    async deleteWorkspaceRaw(requestParameters: DeleteWorkspaceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.workspace === null || requestParameters.workspace === undefined) {
            throw new runtime.RequiredError('workspace','Required parameter requestParameters.workspace was null or undefined when calling deleteWorkspace.');
        }

        if (requestParameters.organization === null || requestParameters.organization === undefined) {
            throw new runtime.RequiredError('organization','Required parameter requestParameters.organization was null or undefined when calling deleteWorkspace.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/faros.sh/api/v1alpha1/organizations/{organization}/workspaces/{workspace}`.replace(`{${"workspace"}}`, encodeURIComponent(String(requestParameters.workspace))).replace(`{${"organization"}}`, encodeURIComponent(String(requestParameters.organization))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete workspace
     */
    async deleteWorkspace(requestParameters: DeleteWorkspaceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteWorkspaceRaw(requestParameters, initOverrides);
    }

    /**
     * Callback from OIDC provider for login flow
     */
    async getCallbackRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ModelsLoginResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/faros.sh/api/v1alpha1/oidc/callback`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ModelsLoginResponseFromJSON(jsonValue));
    }

    /**
     * Callback from OIDC provider for login flow
     */
    async getCallback(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ModelsLoginResponse> {
        const response = await this.getCallbackRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get organization
     */
    async getOrganizationRaw(requestParameters: GetOrganizationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V1alpha1Organization>> {
        if (requestParameters.organization === null || requestParameters.organization === undefined) {
            throw new runtime.RequiredError('organization','Required parameter requestParameters.organization was null or undefined when calling getOrganization.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/faros.sh/api/v1alpha1/organizations/{organization}`.replace(`{${"organization"}}`, encodeURIComponent(String(requestParameters.organization))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => V1alpha1OrganizationFromJSON(jsonValue));
    }

    /**
     * Get organization
     */
    async getOrganization(requestParameters: GetOrganizationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V1alpha1Organization> {
        const response = await this.getOrganizationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get workspace
     */
    async getWorkspaceRaw(requestParameters: GetWorkspaceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V1alpha1Workspace>> {
        if (requestParameters.workspace === null || requestParameters.workspace === undefined) {
            throw new runtime.RequiredError('workspace','Required parameter requestParameters.workspace was null or undefined when calling getWorkspace.');
        }

        if (requestParameters.organization === null || requestParameters.organization === undefined) {
            throw new runtime.RequiredError('organization','Required parameter requestParameters.organization was null or undefined when calling getWorkspace.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/faros.sh/api/v1alpha1/organizations/{organization}/workspaces/{workspace}`.replace(`{${"workspace"}}`, encodeURIComponent(String(requestParameters.workspace))).replace(`{${"organization"}}`, encodeURIComponent(String(requestParameters.organization))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => V1alpha1WorkspaceFromJSON(jsonValue));
    }

    /**
     * Get workspace
     */
    async getWorkspace(requestParameters: GetWorkspaceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V1alpha1Workspace> {
        const response = await this.getWorkspaceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List organizations
     */
    async listOrganizationsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V1alpha1OrganizationList>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/faros.sh/api/v1alpha1/organizations`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => V1alpha1OrganizationListFromJSON(jsonValue));
    }

    /**
     * List organizations
     */
    async listOrganizations(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V1alpha1OrganizationList> {
        const response = await this.listOrganizationsRaw(initOverrides);
        return await response.value();
    }

    /**
     * List workspaces
     */
    async listWorkspacesRaw(requestParameters: ListWorkspacesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V1alpha1WorkspaceList>> {
        if (requestParameters.organization === null || requestParameters.organization === undefined) {
            throw new runtime.RequiredError('organization','Required parameter requestParameters.organization was null or undefined when calling listWorkspaces.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/faros.sh/api/v1alpha1/organizations/{organization}/workspaces`.replace(`{${"organization"}}`, encodeURIComponent(String(requestParameters.organization))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => V1alpha1WorkspaceListFromJSON(jsonValue));
    }

    /**
     * List workspaces
     */
    async listWorkspaces(requestParameters: ListWorkspacesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V1alpha1WorkspaceList> {
        const response = await this.listWorkspacesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Login into Faros
     */
    async loginRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/faros.sh/api/v1alpha1/oidc/login`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Login into Faros
     */
    async login(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.loginRaw(initOverrides);
    }

    /**
     * Callback from OIDC provider for token refresh
     */
    async postCallbackRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/faros.sh/api/v1alpha1/oidc/callback`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Callback from OIDC provider for token refresh
     */
    async postCallback(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.postCallbackRaw(initOverrides);
    }

}
