// Copyright (c) Faros.sh
// Licensed under the Apache License 2.0.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/faroshq/faros/pkg/operator/apis/faros.sh/v1alpha1"
	"github.com/faroshq/faros/pkg/operator/clientset/faros.sh/v1alpha1/versioned/scheme"
	rest "k8s.io/client-go/rest"
)

type FarosV1alpha1Interface interface {
	RESTClient() rest.Interface
	ClustersGetter
	ConfigsGetter
	WorkersGetter
}

// FarosV1alpha1Client is used to interact with features provided by the faros.sh group.
type FarosV1alpha1Client struct {
	restClient rest.Interface
}

func (c *FarosV1alpha1Client) Clusters(namespace string) ClusterInterface {
	return newClusters(c, namespace)
}

func (c *FarosV1alpha1Client) Configs() ConfigInterface {
	return newConfigs(c)
}

func (c *FarosV1alpha1Client) Workers() WorkerInterface {
	return newWorkers(c)
}

// NewForConfig creates a new FarosV1alpha1Client for the given config.
func NewForConfig(c *rest.Config) (*FarosV1alpha1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientFor(&config)
	if err != nil {
		return nil, err
	}
	return &FarosV1alpha1Client{client}, nil
}

// NewForConfigOrDie creates a new FarosV1alpha1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *FarosV1alpha1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new FarosV1alpha1Client for the given RESTClient.
func New(c rest.Interface) *FarosV1alpha1Client {
	return &FarosV1alpha1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := v1alpha1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = scheme.Codecs.WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FarosV1alpha1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
