// Copyright (c) Faros.sh
// Licensed under the Apache License 2.0.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

type ClusterExpansion interface{}

type ConfigExpansion interface{}

type WorkerExpansion interface{}
