//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by kcp code-generator. DO NOT EDIT.

package v1alpha1

import (
	"context"

	kcpclient "github.com/kcp-dev/apimachinery/v2/pkg/client"
	"github.com/kcp-dev/logicalcluster/v3"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/watch"

	tenancyv1alpha1 "github.com/faroshq/faros/pkg/apis/tenancy/v1alpha1"
	tenancyv1alpha1client "github.com/faroshq/faros/pkg/client/clientset/versioned/typed/tenancy/v1alpha1"
)

// OrganizationsClusterGetter has a method to return a OrganizationClusterInterface.
// A group's cluster client should implement this interface.
type OrganizationsClusterGetter interface {
	Organizations() OrganizationClusterInterface
}

// OrganizationClusterInterface can operate on Organizations across all clusters,
// or scope down to one cluster and return a tenancyv1alpha1client.OrganizationInterface.
type OrganizationClusterInterface interface {
	Cluster(logicalcluster.Path) tenancyv1alpha1client.OrganizationInterface
	List(ctx context.Context, opts metav1.ListOptions) (*tenancyv1alpha1.OrganizationList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
}

type organizationsClusterInterface struct {
	clientCache kcpclient.Cache[*tenancyv1alpha1client.TenancyV1alpha1Client]
}

// Cluster scopes the client down to a particular cluster.
func (c *organizationsClusterInterface) Cluster(clusterPath logicalcluster.Path) tenancyv1alpha1client.OrganizationInterface {
	if clusterPath == logicalcluster.Wildcard {
		panic("A specific cluster must be provided when scoping, not the wildcard.")
	}

	return c.clientCache.ClusterOrDie(clusterPath).Organizations()
}

// List returns the entire collection of all Organizations across all clusters.
func (c *organizationsClusterInterface) List(ctx context.Context, opts metav1.ListOptions) (*tenancyv1alpha1.OrganizationList, error) {
	return c.clientCache.ClusterOrDie(logicalcluster.Wildcard).Organizations().List(ctx, opts)
}

// Watch begins to watch all Organizations across all clusters.
func (c *organizationsClusterInterface) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.clientCache.ClusterOrDie(logicalcluster.Wildcard).Organizations().Watch(ctx, opts)
}
