//go:build !ignore_autogenerated

/*
Copyright 2026 The Faros Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Project) DeepCopyInto(out *Project) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new Project.
func (in *Project) DeepCopy() *Project {
	if in == nil {
		return nil
	}
	out := new(Project)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is a deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Project) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectList) DeepCopyInto(out *ProjectList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		l := make([]Project, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&l[i])
		}
		out.Items = l
	}
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new ProjectList.
func (in *ProjectList) DeepCopy() *ProjectList {
	if in == nil {
		return nil
	}
	out := new(ProjectList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is a deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProjectList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectSpec) DeepCopyInto(out *ProjectSpec) {
	*out = *in
	if in.Repository != nil {
		out.Repository = new(ProjectRepositoryBinding)
		*out.Repository = *in.Repository
	}
	if in.Template != nil {
		out.Template = new(ProjectTemplateSpec)
		*out.Template = *in.Template
	}
	if in.Environments != nil {
		l := make([]ProjectEnvironmentSpec, len(in.Environments))
		for i := range in.Environments {
			in.Environments[i].DeepCopyInto(&l[i])
		}
		out.Environments = l
	}
	if in.Development != nil {
		out.Development = new(ProjectDevelopment)
		in.Development.DeepCopyInto(out.Development)
	}
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new ProjectSpec.
func (in *ProjectSpec) DeepCopy() *ProjectSpec {
	if in == nil {
		return nil
	}
	out := new(ProjectSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectRepositoryBinding) DeepCopyInto(out *ProjectRepositoryBinding) {
	*out = *in
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new ProjectRepositoryBinding.
func (in *ProjectRepositoryBinding) DeepCopy() *ProjectRepositoryBinding {
	if in == nil {
		return nil
	}
	out := new(ProjectRepositoryBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectTemplateSpec) DeepCopyInto(out *ProjectTemplateSpec) {
	*out = *in
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new ProjectTemplateSpec.
func (in *ProjectTemplateSpec) DeepCopy() *ProjectTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(ProjectTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectEnvironmentSpec) DeepCopyInto(out *ProjectEnvironmentSpec) {
	*out = *in
	if in.Bindings != nil {
		l := make([]ProjectProviderBindingSpec, len(in.Bindings))
		for i := range in.Bindings {
			in.Bindings[i].DeepCopyInto(&l[i])
		}
		out.Bindings = l
	}
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new ProjectEnvironmentSpec.
func (in *ProjectEnvironmentSpec) DeepCopy() *ProjectEnvironmentSpec {
	if in == nil {
		return nil
	}
	out := new(ProjectEnvironmentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectProviderBindingSpec) DeepCopyInto(out *ProjectProviderBindingSpec) {
	*out = *in
	if in.ResourceRef != nil {
		out.ResourceRef = new(ProjectProviderResourceReference)
		*out.ResourceRef = *in.ResourceRef
	}
	in.Values.DeepCopyInto(&out.Values)
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new ProjectProviderBindingSpec.
func (in *ProjectProviderBindingSpec) DeepCopy() *ProjectProviderBindingSpec {
	if in == nil {
		return nil
	}
	out := new(ProjectProviderBindingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectProviderResourceReference) DeepCopyInto(out *ProjectProviderResourceReference) {
	*out = *in
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new ProjectProviderResourceReference.
func (in *ProjectProviderResourceReference) DeepCopy() *ProjectProviderResourceReference {
	if in == nil {
		return nil
	}
	out := new(ProjectProviderResourceReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectRepositoryStatus) DeepCopyInto(out *ProjectRepositoryStatus) {
	*out = *in
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new ProjectRepositoryStatus.
func (in *ProjectRepositoryStatus) DeepCopy() *ProjectRepositoryStatus {
	if in == nil {
		return nil
	}
	out := new(ProjectRepositoryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectStatus) DeepCopyInto(out *ProjectStatus) {
	*out = *in
	if in.UpdatedAt != nil {
		out.UpdatedAt = in.UpdatedAt.DeepCopy()
	}
	if in.Repository != nil {
		out.Repository = new(ProjectRepositoryStatus)
		*out.Repository = *in.Repository
	}
	if in.Environments != nil {
		l := make([]ProjectEnvironmentStatus, len(in.Environments))
		for i := range in.Environments {
			in.Environments[i].DeepCopyInto(&l[i])
		}
		out.Environments = l
	}
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new ProjectStatus.
func (in *ProjectStatus) DeepCopy() *ProjectStatus {
	if in == nil {
		return nil
	}
	out := new(ProjectStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectEnvironmentStatus) DeepCopyInto(out *ProjectEnvironmentStatus) {
	*out = *in
	if in.Bindings != nil {
		l := make([]ProjectProviderBindingStatus, len(in.Bindings))
		for i := range in.Bindings {
			in.Bindings[i].DeepCopyInto(&l[i])
		}
		out.Bindings = l
	}
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new ProjectEnvironmentStatus.
func (in *ProjectEnvironmentStatus) DeepCopy() *ProjectEnvironmentStatus {
	if in == nil {
		return nil
	}
	out := new(ProjectEnvironmentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectProviderBindingStatus) DeepCopyInto(out *ProjectProviderBindingStatus) {
	*out = *in
	if in.Outputs != nil {
		m := make(map[string]string, len(in.Outputs))
		for k, v := range in.Outputs {
			m[k] = v
		}
		out.Outputs = m
	}
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new ProjectProviderBindingStatus.
func (in *ProjectProviderBindingStatus) DeepCopy() *ProjectProviderBindingStatus {
	if in == nil {
		return nil
	}
	out := new(ProjectProviderBindingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Session) DeepCopyInto(out *Session) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new Session.
func (in *Session) DeepCopy() *Session {
	if in == nil {
		return nil
	}
	out := new(Session)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is a deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Session) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SessionList) DeepCopyInto(out *SessionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		l := make([]Session, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&l[i])
		}
		out.Items = l
	}
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new SessionList.
func (in *SessionList) DeepCopy() *SessionList {
	if in == nil {
		return nil
	}
	out := new(SessionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is a deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SessionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SessionSpec) DeepCopyInto(out *SessionSpec) {
	*out = *in
	if in.ProjectRef != nil {
		out.ProjectRef = new(SessionProjectRef)
		*out.ProjectRef = *in.ProjectRef
	}
	if in.ModelRef != nil {
		out.ModelRef = new(SessionModelRef)
		*out.ModelRef = *in.ModelRef
	}
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new SessionSpec.
func (in *SessionSpec) DeepCopy() *SessionSpec {
	if in == nil {
		return nil
	}
	out := new(SessionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SessionProjectRef) DeepCopyInto(out *SessionProjectRef) {
	*out = *in
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new SessionProjectRef.
func (in *SessionProjectRef) DeepCopy() *SessionProjectRef {
	if in == nil {
		return nil
	}
	out := new(SessionProjectRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SessionStatus) DeepCopyInto(out *SessionStatus) {
	*out = *in
	if in.Checkpoints != nil {
		l := make([]SessionCheckpointStatus, len(in.Checkpoints))
		copy(l, in.Checkpoints)
		out.Checkpoints = l
	}
	if in.UpdatedAt != nil {
		out.UpdatedAt = in.UpdatedAt.DeepCopy()
	}
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new SessionStatus.
func (in *SessionStatus) DeepCopy() *SessionStatus {
	if in == nil {
		return nil
	}
	out := new(SessionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SessionCheckpointStatus) DeepCopyInto(out *SessionCheckpointStatus) {
	*out = *in
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new SessionCheckpointStatus.
func (in *SessionCheckpointStatus) DeepCopy() *SessionCheckpointStatus {
	if in == nil {
		return nil
	}
	out := new(SessionCheckpointStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Model) DeepCopyInto(out *Model) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new Model.
func (in *Model) DeepCopy() *Model {
	if in == nil {
		return nil
	}
	out := new(Model)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is a deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Model) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelList) DeepCopyInto(out *ModelList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		l := make([]Model, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&l[i])
		}
		out.Items = l
	}
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new ModelList.
func (in *ModelList) DeepCopy() *ModelList {
	if in == nil {
		return nil
	}
	out := new(ModelList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is a deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelStatus) DeepCopyInto(out *ModelStatus) {
	*out = *in
	if in.LastUsedAt != nil {
		out.LastUsedAt = in.LastUsedAt.DeepCopy()
	}
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new ModelStatus.
func (in *ModelStatus) DeepCopy() *ModelStatus {
	if in == nil {
		return nil
	}
	out := new(ModelStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SessionModelRef) DeepCopyInto(out *SessionModelRef) {
	*out = *in
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new SessionModelRef.
func (in *SessionModelRef) DeepCopy() *SessionModelRef {
	if in == nil {
		return nil
	}
	out := new(SessionModelRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectDevelopment) DeepCopyInto(out *ProjectDevelopment) {
	*out = *in
	if in.Components != nil {
		l := make([]ProjectComponent, len(in.Components))
		copy(l, in.Components)
		out.Components = l
	}
	if in.Scaffold != nil {
		out.Scaffold = new(ProjectScaffold)
		*out.Scaffold = *in.Scaffold
	}
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new ProjectDevelopment.
func (in *ProjectDevelopment) DeepCopy() *ProjectDevelopment {
	if in == nil {
		return nil
	}
	out := new(ProjectDevelopment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectComponent) DeepCopyInto(out *ProjectComponent) { *out = *in }

// DeepCopy is a deepcopy function, copying the receiver, creating a new ProjectComponent.
func (in *ProjectComponent) DeepCopy() *ProjectComponent {
	if in == nil {
		return nil
	}
	out := new(ProjectComponent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectScaffold) DeepCopyInto(out *ProjectScaffold) { *out = *in }

// DeepCopy is a deepcopy function, copying the receiver, creating a new ProjectScaffold.
func (in *ProjectScaffold) DeepCopy() *ProjectScaffold {
	if in == nil {
		return nil
	}
	out := new(ProjectScaffold)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StudioSearch) DeepCopyInto(out *StudioSearch) {
	*out = *in
	if in.ResourceRef != nil {
		out.ResourceRef = new(ProjectProviderResourceReference)
		*out.ResourceRef = *in.ResourceRef
	}
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new StudioSearch.
func (in *StudioSearch) DeepCopy() *StudioSearch {
	if in == nil {
		return nil
	}
	out := new(StudioSearch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StudioSpec) DeepCopyInto(out *StudioSpec) {
	*out = *in
	in.Search.DeepCopyInto(&out.Search)
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new StudioSpec.
func (in *StudioSpec) DeepCopy() *StudioSpec {
	if in == nil {
		return nil
	}
	out := new(StudioSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StudioStatus) DeepCopyInto(out *StudioStatus) {
	*out = *in
	if in.Search != nil {
		out.Search = new(StudioServiceStatus)
		*out.Search = *in.Search
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new StudioStatus.
func (in *StudioStatus) DeepCopy() *StudioStatus {
	if in == nil {
		return nil
	}
	out := new(StudioStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Studio) DeepCopyInto(out *Studio) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new Studio.
func (in *Studio) DeepCopy() *Studio {
	if in == nil {
		return nil
	}
	out := new(Studio)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is a deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Studio) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StudioList) DeepCopyInto(out *StudioList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		l := make([]Studio, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&l[i])
		}
		out.Items = l
	}
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new StudioList.
func (in *StudioList) DeepCopy() *StudioList {
	if in == nil {
		return nil
	}
	out := new(StudioList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is a deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StudioList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
