//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by kcp code-generator. DO NOT EDIT.

package v1alpha1

import (
	kcptesting "github.com/kcp-dev/client-go/third_party/k8s.io/client-go/testing"
	"github.com/kcp-dev/logicalcluster/v3"

	"context"
	tenancyv1alpha1 "github.com/faroshq/faros/pkg/apis/tenancy/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	"k8s.io/apimachinery/pkg/watch"

	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/testing"

	"k8s.io/apimachinery/pkg/types"

	tenancyv1alpha1client "github.com/faroshq/faros/pkg/client/clientset/versioned/typed/tenancy/v1alpha1"
)

var organizationsResource = schema.GroupVersionResource{Group: "tenancy.faros.sh", Version: "v1alpha1", Resource: "organizations"}
var organizationsKind = schema.GroupVersionKind{Group: "tenancy.faros.sh", Version: "v1alpha1", Kind: "Organization"}

type organizationsClusterClient struct {
	*kcptesting.Fake
}

// Cluster scopes the client down to a particular cluster.
func (c *organizationsClusterClient) Cluster(clusterPath logicalcluster.Path) tenancyv1alpha1client.OrganizationInterface {
	if clusterPath == logicalcluster.Wildcard {
		panic("A specific cluster must be provided when scoping, not the wildcard.")
	}

	return &organizationsClient{Fake: c.Fake, ClusterPath: clusterPath}
}

// List takes label and field selectors, and returns the list of Organizations that match those selectors across all clusters.
func (c *organizationsClusterClient) List(ctx context.Context, opts metav1.ListOptions) (*tenancyv1alpha1.OrganizationList, error) {
	obj, err := c.Fake.Invokes(kcptesting.NewRootListAction(organizationsResource, organizationsKind, logicalcluster.Wildcard, opts), &tenancyv1alpha1.OrganizationList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &tenancyv1alpha1.OrganizationList{ListMeta: obj.(*tenancyv1alpha1.OrganizationList).ListMeta}
	for _, item := range obj.(*tenancyv1alpha1.OrganizationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested Organizations across all clusters.
func (c *organizationsClusterClient) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.InvokesWatch(kcptesting.NewRootWatchAction(organizationsResource, logicalcluster.Wildcard, opts))
}

type organizationsClient struct {
	*kcptesting.Fake
	ClusterPath logicalcluster.Path
}

func (c *organizationsClient) Create(ctx context.Context, organization *tenancyv1alpha1.Organization, opts metav1.CreateOptions) (*tenancyv1alpha1.Organization, error) {
	obj, err := c.Fake.Invokes(kcptesting.NewRootCreateAction(organizationsResource, c.ClusterPath, organization), &tenancyv1alpha1.Organization{})
	if obj == nil {
		return nil, err
	}
	return obj.(*tenancyv1alpha1.Organization), err
}

func (c *organizationsClient) Update(ctx context.Context, organization *tenancyv1alpha1.Organization, opts metav1.UpdateOptions) (*tenancyv1alpha1.Organization, error) {
	obj, err := c.Fake.Invokes(kcptesting.NewRootUpdateAction(organizationsResource, c.ClusterPath, organization), &tenancyv1alpha1.Organization{})
	if obj == nil {
		return nil, err
	}
	return obj.(*tenancyv1alpha1.Organization), err
}

func (c *organizationsClient) UpdateStatus(ctx context.Context, organization *tenancyv1alpha1.Organization, opts metav1.UpdateOptions) (*tenancyv1alpha1.Organization, error) {
	obj, err := c.Fake.Invokes(kcptesting.NewRootUpdateSubresourceAction(organizationsResource, c.ClusterPath, "status", organization), &tenancyv1alpha1.Organization{})
	if obj == nil {
		return nil, err
	}
	return obj.(*tenancyv1alpha1.Organization), err
}

func (c *organizationsClient) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.Invokes(kcptesting.NewRootDeleteActionWithOptions(organizationsResource, c.ClusterPath, name, opts), &tenancyv1alpha1.Organization{})
	return err
}

func (c *organizationsClient) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := kcptesting.NewRootDeleteCollectionAction(organizationsResource, c.ClusterPath, listOpts)

	_, err := c.Fake.Invokes(action, &tenancyv1alpha1.OrganizationList{})
	return err
}

func (c *organizationsClient) Get(ctx context.Context, name string, options metav1.GetOptions) (*tenancyv1alpha1.Organization, error) {
	obj, err := c.Fake.Invokes(kcptesting.NewRootGetAction(organizationsResource, c.ClusterPath, name), &tenancyv1alpha1.Organization{})
	if obj == nil {
		return nil, err
	}
	return obj.(*tenancyv1alpha1.Organization), err
}

// List takes label and field selectors, and returns the list of Organizations that match those selectors.
func (c *organizationsClient) List(ctx context.Context, opts metav1.ListOptions) (*tenancyv1alpha1.OrganizationList, error) {
	obj, err := c.Fake.Invokes(kcptesting.NewRootListAction(organizationsResource, organizationsKind, c.ClusterPath, opts), &tenancyv1alpha1.OrganizationList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &tenancyv1alpha1.OrganizationList{ListMeta: obj.(*tenancyv1alpha1.OrganizationList).ListMeta}
	for _, item := range obj.(*tenancyv1alpha1.OrganizationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

func (c *organizationsClient) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.InvokesWatch(kcptesting.NewRootWatchAction(organizationsResource, c.ClusterPath, opts))
}

func (c *organizationsClient) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (*tenancyv1alpha1.Organization, error) {
	obj, err := c.Fake.Invokes(kcptesting.NewRootPatchSubresourceAction(organizationsResource, c.ClusterPath, name, pt, data, subresources...), &tenancyv1alpha1.Organization{})
	if obj == nil {
		return nil, err
	}
	return obj.(*tenancyv1alpha1.Organization), err
}
