// Copyright (c) Faros.sh
// Licensed under the Apache License 2.0.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/faroshq/faros/pkg/operator/clientset/monitor.faros.sh/v1alpha1/versioned/typed/monitor.faros.sh/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeMonitorV1alpha1 struct {
	*testing.Fake
}

func (c *FakeMonitorV1alpha1) Networks() v1alpha1.NetworkInterface {
	return &FakeNetworks{c}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeMonitorV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
