name: unit-tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit:
    runs-on: [ubuntu-latest]
    timeout-minutes: 8

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: pguser
          POSTGRES_PASSWORD: pgpass
          POSTGRES_DB: faros
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.18
        id: go
      - name: Check out code
        uses: actions/checkout@v2

      - name: Lint
        id: lint
        shell: bash
        run: |
          make lint

      - name: Unit tests
        id: coverage
        shell: bash
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        run: |
          export CI_ONLY=true
          make test
          COVERAGE=$(go tool cover -func profile.cov | grep total: | awk '{print $3}')
          echo "\n\nCoverage will be $COVERAGE"
          echo "::set-env name=COVERAGE::$COVERAGE"
      - run: |
          echo "${{env.COVERAGE}}"
          echo $COVERAGE
      - name: 'Comment PR'
        if: ${{ github.ref != 'refs/heads/main' }}
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `${{env.COVERAGE}}`
            })
