externalHostname: "kcp.dev.faros.sh"
kcp:
#  image: quay.io/faroshq/kcp
#  tag: latest
  volumeClassName: "standard"
  v: "8"
  tokenAuth:
    enabled: true
  hostAliases:
    enabled: true
    values:
    - hostnames:
      - dex.dev.faros.sh
      ip: 127.0.0.1
    - hostnames:
      - kcp.dev.faros.sh
      ip: 127.0.0.1
kcpFrontProxy:
  v: "8"
  openshiftRoute:
    enabled: false
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      nginx.ingress.kubernetes.io/cors-allow-origin: "*"
      nginx.ingress.kubernetes.io/enable-cors: "true"
  certificate:
    issuerSpec:
      selfSigned: {}
  hostAliases:
    enabled: true
    values:
    - hostnames:
      - dex.dev.faros.sh
      ip: 127.0.0.1
    - hostnames:
      - kcp.dev.faros.sh
      ip: 127.0.0.1
oidc:
  enabled: true
  issuerUrl: https://dex.dev.faros.sh
  clientId: faros
  groupClaim: groups
  usernameClaim: email
  usernamePrefix: faros-sso-
  groupsPrefix: faros-sso-
  caSecretName: dex-pki-ca
certificates:
  dnsNames:
  - kcp
  - localhost
  - kcp.dev.faros.sh
